# Generated with resilient-sdk v{{ sdk_version }}
# docker build -t ibmresilient/{{package_name}}:{{version}} .
ARG BASE_IMAGE_REPO=quay.io
# BASE_IMAGE_TAG options: latest, python-312. See https://quay.io/repository/ibmresilient/soarapps-base-docker-image?tab=tags for all options
# use --build-arg BASE_IMAGE_TAG=<tag> to set base image to be built from
ARG BASE_IMAGE_TAG=latest

FROM ${BASE_IMAGE_REPO}/ibmresilient/soarapps-base-docker-image:${BASE_IMAGE_TAG}

ARG APPLICATION={{package_name}}

COPY ./dist /tmp/packages
USER 0
RUN yum -y update && yum clean all
# pip is bootstrapped via ensurepip and removed after install
RUN python3 -m ensurepip --upgrade && \
    python3 -m pip install /tmp/packages/${APPLICATION}-*.tar.gz && \
    python3 -m pip uninstall -y pip setuptools
USER 1001
