#!/bin/bash

if [[ -z "$1" ]]; then
  echo "usage: $0 servername"
  exit 1
fi

portnum=65001
outfile=cert.cer
tempfile=/tmp/tempfile.$$

function finish {
  rm -rf $tempfile
}

trap finish EXIT

certdata=$(openssl s_client -connect $1:$portnum -showcerts -tls1 < /dev/null 2> $tempfile | openssl x509 -outform PEM)

if [ $? -eq 0 ]; then
  echo "$certdata" > $outfile
  echo "Certificate file written to $outfile"
else
  echo "Error retrieving certificate"
  cat $tempfile

  exit 1
fi

