/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// IBM Resilient REST API version 28.1
//
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Co3.Rest.Dto
{
    [DataContract]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BucketBy
    {
        /// <summary>
        /// Unspecified enum value.
        /// </summary>
        [JsonIgnore]
        Undefined,

        /// <summary>
        /// Truncate date object resolution to minute level
        /// </summary>
        [EnumMember(Value = "minute")]
        Minute,

        /// <summary>
        /// Truncate date object resolution to hour level
        /// </summary>
        [EnumMember(Value = "hour")]
        Hour,

        /// <summary>
        /// Truncate date object resolution to day level
        /// </summary>
        [EnumMember(Value = "day")]
        Day,

        /// <summary>
        /// Truncate date object resolution to week level (week starting Sunday)
        /// </summary>
        [EnumMember(Value = "week")]
        Week,

        /// <summary>
        /// Truncate date object resolution to month level
        /// </summary>
        [EnumMember(Value = "month")]
        Month,

        /// <summary>
        /// Truncate date object resolution to year level
        /// </summary>
        [EnumMember(Value = "year")]
        Year,

        /// <summary>
        /// <a href="json_PivotFieldType.html">Date Difference</a> field standard
        /// level
        /// </summary>
        [EnumMember(Value = "default_resolution")]
        DefaultResolution,

        /// <summary>
        /// <a href="json_PivotFieldType.html">Date Difference</a> field fine-grained
        /// level
        /// </summary>
        [EnumMember(Value = "minute_resolution")]
        MinuteResolution
    }
}
