/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Co3.Rest.Dto
{
    [DataContract]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum NewsfeedEntryType
    {
        /// <summary>
        /// Unspecified enum value.
        /// </summary>
        [JsonIgnore]
        Undefined,

        /// <summary>
        /// The object was created.
        /// </summary>
        [EnumMember(Value = "create")]
        Create,

        /// <summary>
        /// The status of the object changed.
        /// </summary>
        [EnumMember(Value = "status_change")]
        StatusChange,

        /// <summary>
        /// The object was assigned to someone new.
        /// </summary>
        [EnumMember(Value = "assigned")]
        Assigned,

        /// <summary>
        /// The object was removed.
        /// </summary>
        [EnumMember(Value = "removed")]
        Removed,

        /// <summary>
        /// The object had members removed.
        /// </summary>
        [EnumMember(Value = "members_removed")]
        MembersRemoved,

        /// <summary>
        /// The object had members added.
        /// </summary>
        [EnumMember(Value = "members_added")]
        MembersAdded,

        /// <summary>
        /// The members list was set.
        /// </summary>
        [EnumMember(Value = "members_set")]
        MembersSet,

        /// <summary>
        /// The members list was unset.
        /// </summary>
        [EnumMember(Value = "members_unset")]
        MembersUnset,

        /// <summary>
        /// The object was modified.
        /// </summary>
        [EnumMember(Value = "modify")]
        Modify,

        /// <summary>
        /// A comment was added to the object.
        /// </summary>
        [EnumMember(Value = "comment_added")]
        CommentAdded,

        /// <summary>
        /// A comment was removed from the object.
        /// </summary>
        [EnumMember(Value = "comment_removed")]
        CommentRemoved,

        /// <summary>
        /// A comment was modified.
        /// </summary>
        [EnumMember(Value = "comment_modified")]
        CommentModified,

        /// <summary>
        /// An attachment was added to the object.
        /// </summary>
        [EnumMember(Value = "attachment_added")]
        AttachmentAdded,

        /// <summary>
        /// An attachment was removed from the object.
        /// </summary>
        [EnumMember(Value = "attachment_removed")]
        AttachmentRemoved,

        /// <summary>
        /// The system task summary was updated.  This happens when the system automatically changes the task list
        /// because of rules.
        /// </summary>
        [EnumMember(Value = "system_task_summary")]
        SystemTaskSummary,

        /// <summary>
        /// Internal use only.
        /// </summary>
        [EnumMember(Value = "imported")]
        Imported,

        /// <summary>
        /// The incident's phase changed.
        /// </summary>
        [EnumMember(Value = "phase_change")]
        PhaseChange,

        /// <summary>
        /// A row was added to a datatable
        /// </summary>
        [EnumMember(Value = "row_added")]
        RowAdded,

        /// <summary>
        /// A row was modified to a datatable
        /// </summary>
        [EnumMember(Value = "row_modified")]
        RowModified,

        /// <summary>
        /// A row was deleted to a datatable
        /// </summary>
        [EnumMember(Value = "row_deleted")]
        RowDeleted
    }
}
