/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// IBM Resilient REST API version 28.1
//
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Co3.Rest.Dto
{
    /// <summary>
    ///  Represents a notification in the system.
    /// 
    ///  <p>Prior to version 28 the template definition and substitution values are provided so the API client can perform
    ///  substitution. Starting with version 28 the template functionality has been been expanded and substitution is
    ///  performed on the server and provided back as part of this object in <a href="json_NotificationDTO.html#reslink_notification_text">notification_text</a>.
    /// 
    ///  <p>Starting with version 29 the following fields will be removed:
    /// 
    ///  <p>inc_id
    ///  <p>inc_training
    ///  <p>task_name
    ///  <p>task_id
    ///  <p>comment_text
    ///  <p>comment_id
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class NotificationDto 
    {
        /// <summary>
        /// The user ID of the person who is to receive the notification.  The
        /// <a href="json_FullOrgDTO.html#reslink_users">fullOrgDTO (users property)</a> contains a list of
        /// all the possible user values.
        /// </summary>
        [JsonProperty("recipient_muser_id")]
        public int RecipientMuserId { get; set; }

        /// <summary>
        /// The notification ID.
        /// </summary>
        [JsonProperty("id")]
        public int Id { get; set; }

        /// <summary>
        /// The date the notification was created.
        /// </summary>
        [JsonProperty("create_date")]
        public DateTime CreateDate { get; set; }

        [JsonProperty("email_date")]
        public DateTime EmailDate { get; set; }

        [JsonProperty("ack_date")]
        public DateTime AckDate { get; set; }

        [JsonProperty("notification_def")]
        public NotificationDefDto NotificationDef { get; set; }

        [JsonProperty("inc_id")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public int IncId { get; set; }

        [JsonProperty("inc_training")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public bool IncTraining { get; set; }

        [JsonProperty("inc_name")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public string IncName { get; set; }

        [JsonProperty("task_name")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public string TaskName { get; set; }

        [JsonProperty("task_id")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public int TaskId { get; set; }

        [JsonProperty("comment_text")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public string CommentText { get; set; }

        [JsonProperty("comment_id")]
        [Obsolete("Deprecated in v28 and will be removed in v29")]
        public int CommentId { get; set; }

        /// <summary>
        /// The user ID of the person who originated the notification.  The
        /// <a href="json_FullOrgDTO.html#reslink_users">fullOrgDTO (users property)</a> contains a list of
        /// all the possible user values.
        /// </summary>
        [JsonProperty("originating_muser_id")]
        public int OriginatingMuserId { get; set; }

        /// <summary>
        /// The user name of the person who originated the notification.
        /// </summary>
        [JsonProperty("originating_muser_name")]
        public string OriginatingMuserName { get; set; }

        /// <summary>
        /// Text of the notification after the notification template has been substituted with values.
        /// </summary>
        [JsonProperty("notification_text")]
        public string NotificationText { get; set; }

        /// <summary>
        /// Object that caused this notification.
        /// </summary>
        [JsonProperty("originating_object")]
        public TypedObjectReferenceDto OriginatingObject { get; set; }
    }
}
