/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Co3.Rest.Dto
{
    /// <summary>
    ///  Represents the permissions that a user has (e.g. whether they can create incidents, are a
    ///  master administrator, etc.).
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class PermsDto 
    {
        /// <summary>
        /// Is the user a master administrator?  Master administrators are allowed to perform
        /// all operations in the system.
        /// </summary>
        [JsonProperty("master_administrator")]
        public bool MasterAdministrator { get; set; }

        /// <summary>
        /// Is the user a "regular" administrator.  Regular administrators can see and modify all incidents and tasks,
        /// but are not allowed modify the organization's configuration settings.
        /// </summary>
        [JsonProperty("administrator")]
        public bool Administrator { get; set; }

        /// <summary>
        /// Is the user an observer?  Observers are allowed to see all incidents and tasks, but cannot make changes
        /// (unless the user is assigned to the incident/task or is also an administrator).
        /// </summary>
        [JsonProperty("observer")]
        public bool Observer { get; set; }

        /// <summary>
        /// Is the user allowed to create incidents?
        /// </summary>
        [JsonProperty("create_incs")]
        public bool CreateIncs { get; set; }
    }
}
