/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Co3.Rest.Dto
{
    /// <summary>
    ///  Contains the full information about an invokable script.
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class ScriptDto : PartialScriptDto
    {
        /// <summary>
        /// The text of the script
        /// </summary>
        [JsonProperty("script_text")]
        public string ScriptText { get; set; }

        /// <summary>
        /// The creator of the script.  This is read-only value.
        /// </summary>
        [JsonProperty("creator_id")]
        public ObjectHandle Creator { get; set; }

        /// <summary>
        /// The user who last modified this script.  This is read-only value.
        /// </summary>
        [JsonProperty("last_modified_by")]
        public ObjectHandle LastModifiedBy { get; set; }

        /// <summary>
        /// The time of the last modification to this script.  This is read-only value.
        /// </summary>
        [JsonProperty("last_modified_time")]
        public DateTime LastModifiedTime { get; set; }

        /// <summary>
        /// The system UUID of the object used as a backup to detect renames
        /// </summary>
        [JsonProperty("uuid")]
        public string Uuid { get; set; }

        /// <summary>
        /// The key which uniquely identifies the object being imported
        /// </summary>
        [JsonProperty("export_key")]
        public string ExportKey { get; set; }
    }
}
