/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Co3.Rest.Dto
{
    /// <summary>
    ///  The results of running a script under the context of an action. Contains messages that resulted from its execution
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class ScriptExecutionDto 
    {
        /// <summary>
        /// The patch to apply to the input objects of the script
        /// </summary>
        [JsonProperty("objects_patch")]
        public ScriptExecutionPatchDto ObjectsPatch { get; set; }

        /// <summary>
        /// The tasks to add to the incident
        /// </summary>
        [JsonProperty("tasks_added")]
        public List<ScriptExecutionPatchDto> TasksAdded { get; set; }

        /// <summary>
        /// The notes to add to the incident
        /// </summary>
        [JsonProperty("notes_added")]
        public List<ScriptExecutionPatchDto> NotesAdded { get; set; }

        /// <summary>
        /// The notes to add to the task
        /// </summary>
        [JsonProperty("task_notes_added")]
        public List<ScriptExecutionPatchDto> TaskNotesAdded { get; set; }

        /// <summary>
        /// The replies to add to the note
        /// </summary>
        [JsonProperty("note_replies")]
        public List<ScriptExecutionPatchDto> NoteReplies { get; set; }

        /// <summary>
        /// The milestones to add to the incident
        /// </summary>
        [JsonProperty("milestones_added")]
        public List<ScriptExecutionPatchDto> MilestonesAdded { get; set; }

        /// <summary>
        /// The artifacts to add to the incident
        /// </summary>
        [JsonProperty("artifacts_added")]
        public List<ScriptExecutionPatchDto> ArtifactsAdded { get; set; }

        /// <summary>
        /// The rows to add to the given data tables
        /// </summary>
        [JsonProperty("rows_added")]
        public Dictionary<string, List<ScriptExecutionPatchDto>> RowsAdded { get; set; }

        /// <summary>
        /// The messages returned from running the script
        /// </summary>
        [JsonProperty("messages")]
        public List<ScriptExecutionMessageDto> Messages { get; set; }
    }
}
