/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Co3.Rest.Dto
{
    [DataContract]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ThreatHitPropertyFormat
    {
        /// <summary>
        /// Unspecified enum value.
        /// </summary>
        [JsonIgnore]
        Undefined,

        /// <summary>
        /// The current default threat hit properties format is NAME_VALUE_PAIRS.
        /// Eventually, the default will be changed to OBJECTS.
        /// </summary>
        [EnumMember(Value = "default")]
        Default,

        /// <summary>
        /// The threat hit properties will be sent as name value pairs.  This is
        /// the default format to maintain backwards compatibility with existing
        /// API clients.  It should not be used.
        /// </summary>
        [EnumMember(Value = "name_value_pairs")]
        NameValuePairs,

        /// <summary>
        /// The threat hit properties will be sent as a list of objects.
        /// 
        /// <pre>
        ///  [
        ///  &nbsp;{
        ///  &nbsp;&nbsp;"name": "Malware name",
        ///  &nbsp;&nbsp;"value": "Trojan.Win32.FlyStudio.O",
        ///  &nbsp;&nbsp;"type": "string"
        ///  &nbsp;},
        ///  &nbsp;{
        ///  &nbsp;&nbsp;...
        ///  &nbsp;},
        ///  ]
        ///  </pre>
        /// </summary>
        [EnumMember(Value = "objects")]
        Objects
    }
}
