/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// IBM Resilient REST API version 28.1
//
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Co3.Rest.Dto
{
    /// <summary>
    ///  Contains the information about a workflow
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class WorkflowDto 
    {
        /// <summary>
        /// The internal ID of the workflow
        /// </summary>
        [JsonProperty("workflow_id")]
        public int Id { get; set; }

        /// <summary>
        /// The display name of the workflow
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The programmatic name of the workflow.
        /// </summary>
        [JsonProperty("programmatic_name")]
        public string ProgrammaticName { get; set; }

        /// <summary>
        /// The object type of the workflow. e.g. Incident, Task, etc.
        /// </summary>
        [JsonProperty("object_type")]
        public ObjectHandle ObjectType { get; set; }

        /// <summary>
        /// The textual description of the workflow
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }

        /// <summary>
        /// The user that created the workflow
        /// </summary>
        [JsonProperty("creator_id")]
        public ObjectHandle CreatorId { get; set; }

        /// <summary>
        /// The user the workflow was last modified by
        /// </summary>
        [JsonProperty("last_modified_by")]
        public ObjectHandle LastModifiedBy { get; set; }

        /// <summary>
        /// The date the workflow was last modified
        /// </summary>
        [JsonProperty("last_modified_time")]
        public DateTime LastModifiedTime { get; set; }

        /// <summary>
        /// This field is used to identify the object during import
        /// </summary>
        [JsonProperty("export_key")]
        public string ExportKey { get; set; }

        /// <summary>
        /// This field is used to identify the object during import
        /// </summary>
        [JsonProperty("uuid")]
        public Guid Uuid { get; set; }

        /// <summary>
        /// Workflow Content (currently Bpmn20 Xml)
        /// </summary>
        [JsonProperty("content")]
        public WorkflowContentDto Content { get; set; }
    }
}
