/*
 * Resilient Systems, Inc. ("Resilient") is willing to license software
 * or access to software to the company or entity that will be using or
 * accessing the software and documentation and that you represent as
 * an employee or authorized agent ("you" or "your") only on the condition
 * that you accept all of the terms of this license agreement.
 *
 * The software and documentation within Resilient's Development Kit are
 * copyrighted by and contain confidential information of Resilient. By
 * accessing and/or using this software and documentation, you agree that
 * while you may make derivative works of them, you:
 *
 * 1)  will not use the software and documentation or any derivative
 *     works for anything but your internal business purposes in
 *     conjunction your licensed used of Resilient's software, nor
 * 2)  provide or disclose the software and documentation or any
 *     derivative works to any third party.
 *
 * THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL RESILIENT BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated>
// IBM Resilient REST API version 28.1
//
// Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Co3.Rest.Dto
{
    /// <summary>
    ///  Workflow parsing problem.
    /// </summary>
    [JsonObject(MemberSerialization.OptIn)]
    public class WorkflowModelProblemDto 
    {
        /// <summary>
        /// The error message generated by the BPMN parser.
        /// </summary>
        [JsonProperty("error")]
        public string Error { get; set; }

        /// <summary>
        /// The line number in the xml where the error was generated.
        /// Generally, the BPMN parser will return either a list of nodes or a line number and column number,
        /// so this element will frequently be 0.
        /// </summary>
        [JsonProperty("line_number")]
        public int LineNumber { get; set; }

        /// <summary>
        /// The column number in the xml where the error was generated.
        /// Generally, the BPMN parser will return either a list of nodes or a line number and column number,
        /// so this element will frequently be 0.
        /// </summary>
        [JsonProperty("column_number")]
        public int ColumnNumber { get; set; }

        /// <summary>
        /// The node(s) which caused the error.
        /// Generally, the BPMN parser will return either a list of nodes or a line number and column number,
        /// so this list will frequently be empty.
        /// Items other than nodes can appear in this list.
        /// </summary>
        [JsonProperty("node_hints")]
        public List<string> NodeHints { get; set; }
    }
}
